wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.21
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.49.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1748531165.0
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 49
      - 53
      - 55
      - 71
      - 103
      - 105
      2:
      - 1
      - 5
      - 9
      - 11
      - 49
      - 53
      - 55
      - 71
      - 103
      - 105
      3:
      - 2
      - 7
      - 13
      - 23
      4: 3.9.21
      5: 0.16.6
      6: 4.49.0
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: val_acc
      5: 1
      6:
      - 1
    - 1: val_recall
      5: 1
      6:
      - 1
    - 1: val_f1
      5: 1
      6:
      - 1
input_shape:
  desc: null
  value:
  - 500
  - 6
  - 1
num_labels:
  desc: null
  value: 12
num_conv_filters:
  desc: null
  value: 24
size:
  desc: null
  value: 128
num_hops:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.0001
