seed: 0

data:
  mode: LOTO
  base_dir: ./data/
  files:
    - USCHAD.npz

model:
  cnn_filters: 64
  attention_size: 128
  attention_num_hops: 16


training:
  epochs: 12
  batch_size: 128
  learning_rate: 0.00005
  early_stopping_patience: 20
  accelerator: auto
  devices: 1

wandb:
  project: ConvAttention


output:
  base_dir: '.'
  save_dir: './chkpts'
